name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        if: runner.os == 'Windows'
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System' --version=3.19.0
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install eigen3:x64-windows
      - name: Install Dependencies
        if: runner.os == 'macOS'
        run: brew install cmake eigen

      - name: Configure
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        if: runner.os != 'Windows'
      - name: Configure
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
        if: runner.os == 'Windows'

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --output-on-failure -C Release --test-dir build
