name: CMake Multi-Platform Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        build_type: [Release, Debug]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
      exclude:
        - os: macos-latest
          c_compiler: cl
        - os: windows-latest
          c_compiler: clang

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        shell: bash
        run: |
          mkdir -p build
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

      - name: Build
        shell: bash
        run: |
          cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        shell: bash
        run: |
          cd build
          ctest --output-on-failure --build-config ${{ matrix.build_type }}
